file: "QMODEL_SBM"
ddp: false
device: gpu

lr: 0.0001
max_epochs: 300
batch_size: 512
num_workers: 0

# NETWORK PARAMETERS
in_channels: 2
hidden_channels: [64, 64, 64]
time_channels: 256
activation: leakyrelu
sigma_min: 1
sigma_max: 10

# SAMPLE GENERATION PARAMETERS
sample_size: 1000000
time_steps: 1000